runtime: custom
env: flex

env_variables:
  DB_CONNECTION_STRING: "mssql+pyodbc://lbarbion:Corporateproject!@corporateproject.database.windows.net:1433/CorporateProject?driver=ODBC+Driver+18+for+SQL+Server"
  SECRET_KEY: "MCSBT"